### ISSUE TITLE
[eclipse-jarsigner-plugin] support signing a file/directory of files instead of attached artifacts 

### ISSUE THREAD

**Issue by laeubi** [eclipse-cbi/org.eclipse.cbi#1]
copied from https://bugs.eclipse.org/bugs/show_bug.cgi?id=570551

The jar-signer plugin [1] supports the following useful configuration options:

- archiveDirectory to specify a directory to scan for jar
- processAttachedArtifacts to enable/disable signing of attached artifacts

it would be good if the eclipse-jarsigner-plugin support this too.

This would allow to easily fix Bug 570315 as it won't require us to do some ugly exec with curl ...

[1]https://maven.apache.org/plugins/maven-jarsigner-plugin/sign-mojo.html

**Comment by laeubi** [comment]
@mbarbero is there any chance this could be made happen in the near future? We need this for https://bugs.eclipse.org/bugs/show_bug.cgi?id=570315 to fix so everything is fine for the 2021-03 release.

**Comment by mbarbero** [comment]
I should be able to do it early Feb.

**Comment by laeubi** [comment]
Thanks for merging, is there a Snapshot repo or something to try this out? Or when is the next release planned?

**Comment by mbarbero** [comment]
Snapshots are available from https://repo.eclipse.org/content/repositories/cbi-snapshots/ (see https://repo.eclipse.org/content/repositories/cbi-snapshots/org/eclipse/cbi/maven/plugins/eclipse-jarsigner-plugin/1.3.0-SNAPSHOT/)
