### ISSUE TITLE
Accidental branch creation

### ISSUE THREAD

**Issue by mbooth101** [eclipse-cbi/org.eclipse.cbi#105]
Hi,

I accidentally pushed a branch named "gpg" to this repo instead of my fork.

I'm happy for it to be deleted if you can do that. I'm not sure if branch deletions count as "rewriting history" so I didn't want to just try it, in case it breaks any clones that people may have. Sorry for the inconvenience!

**Comment by mbarbero** [comment]
I've deleted the `gpg` branch. No worries, as long as it's not the `main|master` branch, it's ok to delete branches.

**Comment by mbooth101** [comment]
Phew :+1:
