### ISSUE TITLE
Deploy flatpak packaging service

### ISSUE THREAD

**Issue by mbooth101** [eclipse-cbi/org.eclipse.cbi#110]
Continuation of https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/697 ...

Linuxtools project are building flatpaks of platform I-builds at [1].

However due to boring technical reasons, the flatpak cannot be built inside a docker container, so we call out to an external webservice to do the heavy lifting. The webservice source lives at CBI project already [2] and works similarly to the DMG packaging service.

The flatpak packaging webservice currently runs on my personal server at [3] but it would be great to have it run at eclipse.org

[1] https://ci.eclipse.org/linuxtools/job/flatpak-nightly/
[2] https://github.com/eclipse-cbi/org.eclipse.cbi/tree/main/webservice/packaging/flatpak
[3] http://eclipse.matbooth.co.uk/jenkins/job/flatpak-packaging-service/

**Comment by SDawley** [comment]
@mbarbero Any idea when we can hope to get started on this? Thanks!

**Comment by mbarbero** [comment]
Will try to make it part of the Q2 plan.

**Comment by akurtakov** [comment]
Just to clarify Q2 of the calendar year, right ?

**Comment by akurtakov** [comment]
Also can we help somehow ?

**Comment by mbarbero** [comment]
yes, 2022Q2. It's all running on internal infra, so there is little help community can provide. However, once we get the ball rolling, we'd appreciate some testings. Thanks!

**Comment by mbarbero** [comment]
> Is there further clarification for the plan?

Plan for Q2 is not defined yet. It's in the list to be triaged. We will keep you posted.

**Comment by SDawley** [comment]
Hello, is there any update on this?

**Comment by akurtakov** [comment]
@agafgfafa Flatpak is the most promising way to ship nicely integrated Eclipse on Linuxes. Unfortunately without being able to build it proper we are stuck to shipping zips to users (even our installer is a zip and not executable!!) . There are already 5 months since this request and the service is written/ready and etc. what is needed is it to be hosted at EF infra. Could this be seriously considered?

**Comment by mbarbero** [comment]
* this is not a showstopper to release the IDE, 
* this request comes from a couple of committers who did not demonstrate strong will from the community to distribute the IDE as flatpak
* this is a request for a brand new service with, I guess, expectation in terms performance, security, availability, and overall longevity. It requires careful planning in its deployment. 

As such, and compared to other services like CI and gitlab, this request has low priority in our limited bandwidth.

Thanks for your patience.

**Comment by akurtakov** [comment]
Here we have a chicken and egg problem as there is no way to have any "official" release. If we speak about community uptake - see http://eclipse.matbooth.co.uk/flatpak/stats.html which shows ~5K monthly updates/installs (of https://flathub.org/apps/details/org.eclipse.Java) which is comparable or even better than half the EPPs shipped (https://www.eclipse.org/downloads/packages/).
We are using such service to produce nightly builds of Eclipse SDK hosted on other machines for development purposes. 
Can the service be hosted without promises  for now?

**Comment by mbarbero** [comment]
FYI, this is still planned to be done by the end of June.

**Comment by akurtakov** [comment]
What is the status here?

**Comment by akurtakov** [comment]
It's end of July. Is there any hope?

**Comment by mbooth101** [comment]
> 
>     * this is a request for a brand new service with, I guess, expectation in terms performance, security, availability, and overall longevity. It requires careful planning in its deployment.
> 

As mentioned in the original ticket I designed it to be just like the existing Mac DMG signing service. I hoped having a precedent would make it easier to get this deployed.

If there some change I can make to the service to make it easier to deploy, please let me know.

**Comment by akurtakov** [comment]
Is there any hope at all for this one?
