### ISSUE TITLE
CBI repo down?

### ISSUE THREAD

**Issue by laeubi** [eclipse-cbi/org.eclipse.cbi#171]
At Tycho I see the following error now on the license checks:

Error:  Error resolving version for plugin 'org.eclipse.dash:license-tool-plugin' from the repositories [local (/home/runner/.m2/repository), dash-licenses-snapshots (https://repo.eclipse.org/content/repositories/dash-licenses-snapshots/), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]

**Comment by mbarbero** [comment]
Fixed via https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1636.
