### ISSUE TITLE
Before failing to sign because of a failing TSA, try a couple of others before returning

### ISSUE THREAD

**Issue by mbarbero** [eclipse-cbi/org.eclipse.cbi#27]
(moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=552267)

List of TSA:

(from https://gist.github.com/Manouchehri/fd754e402d98430243455713efada710)
http://timestamp.globalsign.com/scripts/timstamp.dll
https://timestamp.geotrust.com/tsa
http://timestamp.comodoca.com/rfc3161
http://timestamp.wosign.com
http://tsa.startssl.com/rfc3161
http://time.certum.pl
http://timestamp.digicert.com
https://freetsa.org
http://dse200.ncipher.com/TSS/HttpTspServer
http://tsa.safecreative.org
http://zeitstempel.dfn.de
https://ca.signfiles.com/tsa/get.aspx
http://services.globaltrustfinder.com/adss/tsa
https://tsp.iaik.tugraz.at/tsp/TspRequest
http://timestamp.apple.com/ts01
http://timestamp.entrust.net/TSS/RFC3161sha2TS

and 

(from https://stackoverflow.com/a/25053511)

https://freetsa.org - Supports HTTP, HTTPS and TCP transports and has other features
http://time.certum.pl
http://dse200.ncipher.com/TSS/HttpTspServer
http://tsa.safecreative.org - 5 free requests per day (may not be valid as root CA is 'test') - Safe Creative TSA is no longer active
http://zeitstempel.dfn.de
http://tsa.tecxoft.com - Requires registration
http://timestamp.comodoca.com/rfc3161
http://sha256timestamp.ws.symantec.com/sha256/timestamp
https://timestamp.geotrust.com/tsa
http://timestamp.globalsign.com/scripts/timstamp.dll
https://ca.signfiles.com/tsa/get.aspx
http://services.globaltrustfinder.com/adss/tsa
https://tsp.iaik.tugraz.at/tsp/TspRequest

A single TSA can be configure so far https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/webservice/signing/jar/src/main/java/org/eclipse/cbi/webservice/signing/jar/SigningServer.java#L64

**Comment by mbooth101** [comment]
Maybe stalebot can be configured to ignore "help wanted" bugs, or at least wait more than a couple of months?

**Comment by mbarbero** [comment]
I actually like the recurring nagging :)

**Comment by akurtakov** [comment]
Is there anything still needed here?

**Comment by mbarbero** [comment]
> Is there anything still needed here?

yes, it's still desirable.
