### ISSUE TITLE
Window Signing Service fails silently when timeserver fails

### ISSUE THREAD

**Issue by netomi** [eclipse-cbi/org.eclipse.cbi#360]
Currently, a single timeserver url is configured, when this timeserver fails to send a valid response (e.g. 502 error), the signing service will also fail silently and produce this log:

```
2023-10-30 21:54:21 ERROR ProcessExecutor$BasicImpl:186 - Process '/usr/local/bin/osslsigncode' exited with value '255'
2023-10-30 21:54:21 ERROR ProcessExecutor$BasicImpl:188 - Process '/usr/local/bin/osslsigncode' output:
Failed to convert timestamp reply from http://timestamp.sectigo.com; HTTP status 502
Authenticode timestamping failed
Use the "-ts" option to add the RFC3161 Time-Stamp Authority or choose another one Authenticode Time-Stamp Authority
Failed
```

Need to investigate how we can make this more fail-safe e.g. by allowing multiple timeservers and retry with a different one in case of failure.

**Comment by netomi** [comment]
The osslsigncode tool supports specifying multiple timeservers and if one fails, will try the others before failing:

```
tn@proteus:~/workspace/eclipse/eclipse-cbi/osslsigncode/tests/certs$ ../../build/osslsigncode sign -pkcs12 legacy.p12 -pass passme -t http://timestamp1.sectigo.com -t http://timestamp.sectigo.com -verbose -in GameOverlayRenderer64.dll test.dll
Connecting to http://timestamp1.sectigo.com
CURL failure: Couldn't resolve host name http://timestamp1.sectigo.com
Connecting to http://timestamp.sectigo.com
Succeeded
```

So just updating the config should solve the problem.

**Comment by netomi** [comment]
that is the list of timeservers that were used by adoptium prior to use the signing service:

```
http://timestamp.comodoca.com/authenticode -> OK 02/08/2030 -> Sectigo RSA Time Stamping Signer #1
http://timestamp.sectigo.com -> OK 02/08/2030 -> Sectigo RSA Time Stamping Signer #1 .. same as previous but with another url
http://timestamp.comodoca.com/rfc3161 -> OK 02/08/2030 -> Sectigo RSA Time Stamping Signer #1 .. same as previous but with another url
http://tsa.startssl.com/rfc3161 -> OK 15/08/2028 -> WoSign Time Stamping Signer ( buyed by WoTrus )
http://tsa.starfieldtech.com -> OK 17/09/2027 -> Starfield Timestamp Authority - G2
http://timestamp.globalsign.com/scripts/timstamp.dll -> OK 24/06/2027 -> GlobalSign TSA for MS Authenticode - G2
http://timestamp.digicert.com -> OK 22/10/2024 -> DigiCert Timestamp Responder
;http://timestamp.verisign.com/scripts/timstamp.dll -> Expire to soon 30/12/2020 -> Symantec Time Stamping Services Signer - G4
```

this is the list of timeservers that are found in the bash completion script of the osslsigncode tool

```
    timestamps="http://timestamp.digicert.com
        http://time.certum.pl
        http://timestamp.sectigo.com
        http://timestamp.globalsign.com/?signature=sha2"
```

**Comment by netomi** [comment]
Here is a list of timeservers that support https:

https://stackoverflow.com/a/76026618/3784643

**Comment by netomi** [comment]
we should use also rfc3161 compliant timeservers using -ts

e.g.

-ts https://tsp.iaik.tugraz.at/tsp/TspRequest

**Comment by netomi** [comment]
btw. in https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/webservice/signing/windows/etc/windows-signing-service.properties#L66 the timeserver url is set to http://timestamp.verisign.com/scripts/timestamp.dll

however, the production settings are overridden in:

https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/webservice/signing/windows/service.jsonnet#L153

to

http://timestamp.sectigo.com

**Comment by netomi** [comment]
right now it is only possible to define a single url for the timeserver, this needs to be extended to be able to provide a list of urls that are then passed properly to the osslsigncode tool.

**Comment by mbarbero** [comment]
See also #27
