### ISSUE TITLE
CBI contains incorrect license declarations

### ISSUE THREAD

**Issue by mbooth101** [eclipse-cbi/org.eclipse.cbi#98]
I assume we are supposed to be a EPL-2.0 project because most eclipse.org projects are, and that is the license contained in https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/LICENSE

However, the pom.xml still says EPL-1.0: https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/pom.xml#L17-L18

And source file headers still say EPL-1.0: https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/common/src/main/java/org/eclipse/cbi/common/util/ByteBufferRecord.java#L1-L10

However I don't recall any licence change announcement for CBI, should the license declarations in the pom/source be updated, or is the LICENSE file incorrect?

**Comment by akurtakov** [comment]
On Wed, Jan 12, 2022 at 2:26 PM Mat Booth ***@***.***> wrote:

> I assume we are supposed to be a EPL-2.0 project because most eclipse.org
> projects are, and that is the license contained in
> https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/LICENSE
>
> However, the pom.xml still says EPL-1.0:
> https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/pom.xml#L17-L18
>
> And source file headers still say EPL-1.0:
> https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/common/src/main/java/org/eclipse/cbi/common/util/ByteBufferRecord.java#L1-L10
>
> However I don't recall any licence change announcement for CBI, should the
> license declarations in the pom/source be updated, or is the LICENSE file
> incorrect?
>

IMHO, there is no need to announce such changes anymore  - EPL 2.0 is the
successor. Wherever it says EPL 1.0 still needs updating to EPL 2.0.

**Comment by mbooth101** [comment]
Cool, updated the issue name accordingly.
